export const EMOJIS = [
    {team:'Blues'     , longName: 'Carlton'           , emoji:':blues:'}    ,
    {team:'Bombers'   , longName: 'Essendon'          , emoji:':dons:'}     ,
    {team:'Bulldogs'  , longName: 'Western Bulldogs'  , emoji:':bulldogs:'} ,
    {team:'Cats'      , longName: 'Geelong Cats'      , emoji:':cats:'}     ,
    {team:'Crows'     , longName: 'Adelaide Crows'    , emoji:':crows:'}    ,
    {team:'Demons'    , longName: 'Melbourne'         , emoji:':dees:'}     ,
    {team:'Dockers'   , longName: 'Fremantle'         , emoji:':freo:'}     ,
    {team:'Eagles'    , longName: 'West Coast Eagles' , emoji:':eagles:'}   ,
    {team:'Giants'    , longName: 'GWS Giants'        , emoji:':gaints:'}   ,
    {team:'Hawks'     , longName: 'Hawthorn'          , emoji:':hawks:'}    ,
    {team:'Kangaroos' , longName: 'North Melbourne'   , emoji:':kangas:'}   ,
    {team:'Lions'     , longName: 'Brisbane Lions'    , emoji:':lions:'}    ,
    {team:'Magpies'   , longName: 'Collingwood'       , emoji:':pies:'}     ,
    {team:'Power'     , longName: 'Port Adelaide'     , emoji:':port:'}     ,
    {team:'Saints'    , longName: 'St Kilda'          , emoji:':saints:'}   ,
    {team:'Suns'      , longName: 'Gold Coast Suns'   , emoji:':suns:'}     ,
    {team:'Swans'     , longName: 'Sydney Swans'      , emoji:':swans:'}    ,
    {team:'Tigers'    , longName: 'Richmond'          , emoji:':tigers:'}   ,
  ];
