export const returned = { title: 'West Coast Eagles Vs Fremantle - Match Centre - AFL.com.au',
  hometeam: 'West Coast Eagles',
  awayteam: 'Fremantle',
  homescore:
   [ { stat: 'S. Goals\n                                        0' },
     { stat: 'Goals\n                                        8' },
     { stat: 'Behinds\n                                        4' },
     { stat: 'Total\n                                        52' } ],
  awayscore:
   [ { stat: 'S. Goals\n                                        0' },
     { stat: 'Goals\n                                        8' },
     { stat: 'Behinds\n                                        4' },
     { stat: 'Total\n                                        52' } ],
  comments:
   [ { comment: 'The siren has sounded to end Q4.' },
     { comment: 'The difference between the two sides had been in West Coast\'s run and carry on the outside. They have created 95 more handball receives and 177 uncontested possessions allowing them to create ten more scores from turnovers.' },
     { comment: 'GOALEagles (Josh J. Kennedy)' },
     { comment: 'West Coast Eagles InterchangeDom Sheed replaces Jack Redden due to the blood rule.' },
     { comment: 'BEHINDEagles (Drew Petrie)' },
     { comment: 'Even in the latter half of the final quarter, West Coast continue to find forward 50 targets. They have seventeen marks inside 50, which has translated to 8.6.54 from set shots.' },
     { comment: 'BEHINDEagles (Lewis Jetta)' },
     { comment: 'Last season, West Coast were ranked 12th for scoring from centre bounces. The addition of Sam Mitchell, who has had eleven score involvements has made a difference today with the Eagles launching 5.2.32 from this source.' },
     { comment: 'Fremantle have been far more effective from clearances in the second half. They have generated four goals from seven clearances compared to zero and from eleven in the first half.' },
     { comment: 'GOALEagles (Mark LeCras)' },
     { comment: 'GOALDockers (Hayden Crozier)' },
     { comment: 'BEHINDDockers (Rushed)' },
     { comment: 'BEHINDEagles (Mark LeCras)' },
     { comment: 'Since quarter time, Danyle Pearce has had a game high 356 metres gained.' },
     { comment: 'BEHINDDockers (Danyle Pearce)' },
     { comment: 'Despite winning just 3 less clearances, Fremantle has created just two more goals from stoppages. Nathan Fyfe has exercised his dominance in this area with six of their sixteen clearances.' },
     { comment: 'GOALDockers (Bradley Hill)' },
     { comment: 'Q4 is now underway.' },
     { comment: 'The siren has sounded to end Q3.' },
     { comment: 'GOALEagles (Nathan Vardy)' },
     { comment: 'West Coast have completely dominated from centre clearances (136) and have taken full advantage creating five goals from this source.' },
     { comment: 'GOALEagles (Lewis Jetta)' },
     { comment: 'Michael Walters has had an impact for the Dockers from few opportunities. He has seven score involvements and five inside 50\'s from just 11 disposals.' },
     { comment: 'BEHINDEagles (Rushed)' },
     { comment: 'BEHINDEagles (Josh Hill)' },
     { comment: 'The grounds size has aided free flowing scoring this quarter. Fremantle has launched a goal from 60 per cent of inside 50\'s and West Coast has generated a goal from 40 per cent.' },
     { comment: 'GOALDockers (Hayden Ballantyne)' },
     { comment: 'BEHINDEagles (Drew Petrie)' },
     { comment: 'GOALDockers (Shane Kersten)' },
     { comment: 'A key difference between the two sides has been West Coast\'s ability to launch goals from clearances. From six additional clearances they have created five more goals than the Dockers.' },
     { comment: 'GOALEagles (Luke Shuey)' },
     { comment: 'BEHINDDockers (Michael Walters)' },
     { comment: 'Josh Kennedy has recorded five goals against Fremantle for the second time in a preseason game. He also has four marks inside 50 and five score involvements.' },
     { comment: 'GOALEagles (Josh J. Kennedy)' },
     { comment: 'Since the first quarter, Fremantle have been more effective at transitioning from their defensive 50. They have launched two goals from five intercepts in this zone.' },
     { comment: 'GOALDockers (Ed Langdon)' },
     { comment: 'Q3 is now underway.' },
     { comment: 'The siren has sounded to end Q2.' },
     { comment: 'GOALDockers (Bradley Hill)' },
     { comment: 'West Coast ball movement enabled them to launch 6.4.40 from just 24 intercepts that half. Mark Lecras was a standout with a game high 305 metres gained and eight score involvements.' },
     { comment: 'GOALEagles (Josh Hill)' },
     { comment: 'West Coast has amassed 96 more uncontested possessions and 13 more inside 50\'s. They have been efficient from their defensive midfield thisquarter, generating a goal from 60 per cent intercepts.' },
     { comment: 'BEHINDEagles (Mark LeCras)' },
     { comment: 'BEHINDDockers (Michael Walters)' },
     { comment: 'GOALEagles (Josh Hill)' },
     { comment: 'That goal to Hayden Ballantyne was the Dockers first goal generated from 16 defensive half chains. Whilst, Nathan Fyfe has contributed valiantly with three centre clearances and two score involvements.' },
     { comment: 'GOALDockers (Hayden Ballantyne)' },
     { comment: 'In the previous JLT Community Series match, the Eagles created just five marks inside 50. Today they have eight and have been effective from set shots with five goals from seven opportunities.' },
     { comment: 'GOALEagles (Josh J. Kennedy)' },
     { comment: 'West Coast has created 52 more handball receives and their disposal efficiency is 81 per cent. This run and carry has enabled them to generate a goal from 43.75 per cent of inside 50\'s' },
     { comment: 'GOALEagles (Mark LeCras)' },
     { comment: 'BEHINDDockers (Michael Walters)' },
     { comment: 'West Coast has created just two more intercepts across their midfield, but have launched 2.1.13 to 0.0.0 from this zone.' },
     { comment: 'GOALEagles (Jamie Cripps)' },
     { comment: 'Q2 is now underway.' },
     { comment: 'West Coast utilized their centre clearance dominance and an open forward 50 to full effect in that quarter. They won five centre clearances, launching three of their four goals from this source.' },
     { comment: 'The siren has sounded to end Q1.' },
     { comment: 'Sharrod Wellingham has continued on his form from last week with a gamehigh 8 uncontested possessions and four score involvements. New recruit; Sam Mitchell has been very effective with five score involvements from ten disposals.' },
     { comment: 'GOALEagles (Josh J. Kennedy)' },
     { comment: 'GOALEagles (Jack Darling)' },
     { comment: 'BEHINDEagles (Mark Hutchings)' },
     { comment: 'Fremantle has won four of the last five clearances. However, West Coast\'s disposal efficiency is 11 per cent greater and they lead the uncontested possession count by 46.' },
     { comment: 'GOALDockers (Michael Apeness)' },
     { comment: 'Fremantle have created just one inside 50 from eight defensive half chains. In comparison, West Coast has transitioned swiftly launching an inside 50 from 60 per cent of defensive half chains.' },
     { comment: 'BEHINDEagles (Josh J. Kennedy)' },
     { comment: 'The Eagles have creates eight inside 50\'s to two so far and been more efficient going inside, launching 3.1.20 to 0.0.0' },
     { comment: 'BEHINDEagles (Jack Darling)' },
     { comment: 'West Coast are dominating from centre clearances early on. They have won the first three centre bounces and have launched 2.1.13 from this source.' },
     { comment: 'GOALEagles (Jamie Cripps)' },
     { comment: 'GOALEagles (Josh J. Kennedy)' },
     { comment: 'GOALEagles (Mark LeCras)' },
     { comment: 'BEHINDEagles (Lewis Jetta)' },
     { comment: 'Q1 is now underway.' },
     { comment: 'West Coast and Fremantle were very different teams on offense in 2016. The Eagles generated a goal from 27.4 per cent of inside 50\'s. Fremantle were ranked third last, launching a goal from just 22.7 per cent of inside attack.' },
     { comment: 'In last week\'s 33 point loss to GWS, Sharrod Wellingham was a bright light. He had a gamehigh 19 uncontested possessions and 651 metres gaines as well as 9 makrs and 3 clearances.' },
     { comment: 'No changes for Dockers.' },
     { comment: 'Ins for Eagles: S.Mitchell, M.LeCras, A.Gaff, B.Sheppard, M.Priddis, L.Shuey, J.Cripps, J.Kennedy, J.McGovern, D.Petrie, S.Hurn, S.Butler, J.Darling, J.Hill' },
     { comment: 'Outs for Eagles: W.Schofield, T.Cole, L.Partington, T.Lamb, J.Rotham, F.Mcinnes, K.Mutimer, M.Karpany, T.Gorter, J.Snadden, T.Bayok, J.Waterman, P.Brophy, F.Watson' },
     { comment: 'Welcome to Wonthella Oval for the West Coast Eagles v Fremantle Round 2 clash.' } ],
  stats:
   [ { stat: '' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: 'West Coast Eagles Interchange' },
     { stat: 'BEHIND' },
     { stat: '' },
     { stat: 'BEHIND' },
     { stat: '' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: 'GOAL' },
     { stat: 'BEHIND' },
     { stat: 'BEHIND' },
     { stat: '' },
     { stat: 'BEHIND' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: '' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: 'West Coast have completely dominated from centre clearances (13' },
     { stat: 'GOAL' },
     { stat: '' },
     { stat: 'BEHIND' },
     { stat: 'BEHIND' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: 'BEHIND' },
     { stat: 'GOAL' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: 'BEHIND' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: '' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: '' },
     { stat: 'BEHIND' },
     { stat: 'BEHIND' },
     { stat: 'GOAL' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: 'BEHIND' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: '' },
     { stat: '' },
     { stat: '' },
     { stat: 'Sharrod Wellingham has continued on his form from last week with a game' },
     { stat: 'GOAL' },
     { stat: 'GOAL' },
     { stat: 'BEHIND' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: '' },
     { stat: 'BEHIND' },
     { stat: '' },
     { stat: 'BEHIND' },
     { stat: '' },
     { stat: 'GOAL' },
     { stat: 'GOAL' },
     { stat: 'GOAL' },
     { stat: 'BEHIND' },
     { stat: '' },
     { stat: '' },
     { stat: 'In last week\'s 33 point loss to GWS, Sharrod Wellingham was a bright light. He had a game' },
     { stat: '' },
     { stat: '' },
     { stat: '' },
     { stat: '' } ],
  times:
   [ { time: 'Q4 22:11' },
     { time: 'Q4 21:16' },
     { time: 'Q4 21:50' },
     { time: 'Q4 20:27' },
     { time: 'Q4 16:29' },
     { time: 'Q4 16:16' },
     { time: 'Q4 15:14' },
     { time: 'Q4 12:17' },
     { time: 'Q4 10:50' },
     { time: 'Q4 09:33' },
     { time: 'Q4 07:49' },
     { time: 'Q4 06:48' },
     { time: 'Q4 04:15' },
     { time: 'Q4 04:55' },
     { time: 'Q4 03:58' },
     { time: 'Q4 02:55' },
     { time: 'Q4 00:30' },
     { time: 'Q4 00:00' },
     { time: 'Q3 22:10' },
     { time: 'Q3 21:54' },
     { time: 'Q3 21:31' },
     { time: 'Q3 19:09' },
     { time: 'Q3 17:14' },
     { time: 'Q3 16:04' },
     { time: 'Q3 15:12' },
     { time: 'Q3 13:21' },
     { time: 'Q3 13:04' },
     { time: 'Q3 12:48' },
     { time: 'Q3 10:48' },
     { time: 'Q3 08:18' },
     { time: 'Q3 08:17' },
     { time: 'Q3 06:13' },
     { time: 'Q3 06:45' },
     { time: 'Q3 04:19' },
     { time: 'Q3 03:10' },
     { time: 'Q3 03:42' },
     { time: 'Q3 00:00' },
     { time: 'Q2 22:06' },
     { time: 'Q2 21:22' },
     { time: 'Q2 21:03' },
     { time: 'Q2 18:21' },
     { time: 'Q2 17:43' },
     { time: 'Q2 16:03' },
     { time: 'Q2 14:53' },
     { time: 'Q2 13:38' },
     { time: 'Q2 12:49' },
     { time: 'Q2 10:10' },
     { time: 'Q2 08:10' },
     { time: 'Q2 07:11' },
     { time: 'Q2 05:03' },
     { time: 'Q2 05:40' },
     { time: 'Q2 03:10' },
     { time: 'Q2 02:02' },
     { time: 'Q2 01:24' },
     { time: 'Q2 00:00' },
     { time: 'Q1 22:24' },
     { time: 'Q1 22:14' },
     { time: 'Q1 21:26' },
     { time: 'Q1 21:40' },
     { time: 'Q1 19:05' },
     { time: 'Q1 17:49' },
     { time: 'Q1 17:44' },
     { time: 'Q1 15:04' },
     { time: 'Q1 13:49' },
     { time: 'Q1 11:28' },
     { time: 'Q1 10:50' },
     { time: 'Q1 10:48' },
     { time: 'Q1 05:08' },
     { time: 'Q1 05:54' },
     { time: 'Q1 04:34' },
     { time: 'Q1 02:41' },
     { time: 'Q1 01:37' },
     { time: 'Q1 00:00' },
     { time: 'Q0 00:10' },
     { time: 'Q0 00:10' },
     { time: 'Q0 -00:-24' },
     { time: 'Q0 -00:-26' },
     { time: 'Q0 -00:-27' },
     { time: 'Q0 -00:-30' } ] };
